CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_ID      START WITH 133 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_ID            START WITH 6 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_PATH_ID START WITH 166 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_STATION_ID          START WITH 26 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_TRAIN_ID            START WITH 40 BELONGS_TO_TABLE;
CREATE SEQUENCE PUBLIC.SYSTEM_SEQUENCE_TIME_ID             START WITH 730 BELONGS_TO_TABLE;

CREATE CACHED TABLE PUBLIC.ROUTE( 
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ROUTE_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_ID, 
    NAME VARCHAR(255),
    NAME_ARABIC VARCHAR(255),
    ROUTE_CODE VARCHAR(255), 
    ROUTE_COLOR VARCHAR(255) 
);
ALTER TABLE PUBLIC.ROUTE ADD CONSTRAINT PUBLIC.CONSTRAINT_ROUTE_KEY PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.ROUTE_POINT( 
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_ID, 
    LAT DOUBLE NOT NULL, 
    LNG DOUBLE NOT NULL, 
    STATION_ID BIGINT 
);
ALTER TABLE PUBLIC.ROUTE_POINT ADD CONSTRAINT PUBLIC.CONSTRAINT_ROUTEPOINT PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.ROUTE_POINT_ROUTES( 
    ROUTE_POINTS_ID BIGINT NOT NULL, 
    ROUTES_ID BIGINT NOT NULL 
);

CREATE CACHED TABLE PUBLIC.ROUTE_POINT_PATH( 
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_PATH_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_ROUTE_POINT_PATH_ID, 
    POINT_INDEX INTEGER NOT NULL, 
    ROUTE_ID BIGINT, 
    ROUTE_POINT_ID BIGINT 
);
ALTER TABLE PUBLIC.ROUTE_POINT_PATH ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.USERS( 
    USERNAME VARCHAR(60) NOT NULL, 
    FULL_NAME VARCHAR(255), 
    GENDER VARCHAR(255), 
    PASSWORD VARCHAR(255), 
    ROLE VARCHAR(255) 
);
ALTER TABLE PUBLIC.USERS ADD CONSTRAINT PUBLIC.CONSTRAINT_4D4 PRIMARY KEY(USERNAME);

CREATE CACHED TABLE PUBLIC.STATION( 
    ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_STATION_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_STATION_ID, 
    NAME VARCHAR(255),
    NAME_ARABIC VARCHAR(255),
    STATION_CODE VARCHAR(255), 
    STATION_TYPE VARCHAR(255), 
    ROUTE_POINT_ID BIGINT 
);
ALTER TABLE PUBLIC.STATION ADD CONSTRAINT PUBLIC.CONSTRAINT_B PRIMARY KEY(ID);

CREATE CACHED TABLE PUBLIC.TRAIN( 
    TRAIN_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_TRAIN_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_TRAIN_ID, 
    TRAIN_MODEL VARCHAR(25),
    ROUTE_ID BIGINT 
);
ALTER TABLE PUBLIC.TRAIN ADD CONSTRAINT PUBLIC.TRAIN_KEY PRIMARY KEY(TRAIN_ID);

CREATE CACHED TABLE PUBLIC.TRAIN_TIME( 
    TIME_ID BIGINT DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_TIME_ID) NOT NULL NULL_TO_DEFAULT SEQUENCE PUBLIC.SYSTEM_SEQUENCE_TIME_ID, 
    FORWARD BOOLEAN,
    HOUR SMALLINT,
    MINUTE SMALLINT,
    TIME_TYPE VARCHAR(25),
    TRIP_MINUTES INTEGER,
    STATION_ID BIGINT,
    TRAIN_TRAIN_ID BIGINT 
);
ALTER TABLE PUBLIC.TRAIN_TIME ADD CONSTRAINT PUBLIC.TRAIN_TIME_KEY PRIMARY KEY(TIME_ID);